all:
	g++ -std=c++11 -g -o stall_status stall_status.cc monitor.pb.cc -L../third/slash/output/lib -L../third/pink/output/lib -lslash -lpink -I../third/slash/output/include -I../third/pink/output/include -I../third/pink/output -lprotobuf -lpthread
